// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-72iimGhndmrJ37niaxA8Vt9LevwwnQ',
    appId: '1:1088895098059:web:abd2ee493ca9156f6c4f4e',
    messagingSenderId: '1088895098059',
    projectId: 'furniture-shopping-a552f',
    authDomain: 'furniture-shopping-a552f.firebaseapp.com',
    storageBucket: 'furniture-shopping-a552f.firebasestorage.app',
    measurementId: 'G-F6KY8V7X1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgyURVXtcFN-ZlxtlF4MagUsKyzKOIYs4',
    appId: '1:1088895098059:android:b3e859442f0e9fcc6c4f4e',
    messagingSenderId: '1088895098059',
    projectId: 'furniture-shopping-a552f',
    storageBucket: 'furniture-shopping-a552f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbw_VgmHnVXzi1OKmkgb3MBz3vKVLxEqw',
    appId: '1:1088895098059:ios:8dcf847b96f024ed6c4f4e',
    messagingSenderId: '1088895098059',
    projectId: 'furniture-shopping-a552f',
    storageBucket: 'furniture-shopping-a552f.firebasestorage.app',
    iosBundleId: 'com.example.furnitureShoppinUi',
  );
}
